import uuid
import enum
from datetime import datetime

from sqlalchemy import JSON, DateTime, ForeignKey, String, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, UUIDPrimaryKeyMixin


class AuditAction(str, enum.Enum):
    ANSWER_VERIFIED = "ANSWER_VERIFIED"
    ANSWER_UNVERIFIED = "ANSWER_UNVERIFIED"
    ANSWER_REVIEWED = "ANSWER_REVIEWED"
    ANSWER_SUPERSEDED = "ANSWER_SUPERSEDED"
    ANSWER_CHALLENGED = "ANSWER_CHALLENGED"
    CHALLENGE_ACCEPTED = "CHALLENGE_ACCEPTED"
    CHALLENGE_REJECTED = "CHALLENGE_REJECTED"
    ANSWER_VERSION_CREATED = "ANSWER_VERSION_CREATED"
    QUESTION_VERSION_CREATED = "QUESTION_VERSION_CREATED"
    QUESTION_CHANGE_REQUESTED = "QUESTION_CHANGE_REQUESTED"
    QUESTION_CHANGE_REQUEST_REVIEWED = "QUESTION_CHANGE_REQUEST_REVIEWED"
    QUESTION_ARCHIVED = "QUESTION_ARCHIVED"
    QUESTION_RESTORED = "QUESTION_RESTORED"
    ANSWER_ARCHIVED = "ANSWER_ARCHIVED"
    ANSWER_RESTORED = "ANSWER_RESTORED"
    DEPARTMENT_OWNER_ASSIGNED = "DEPARTMENT_OWNER_ASSIGNED"
    DEPARTMENT_OWNER_REMOVED = "DEPARTMENT_OWNER_REMOVED"
    QUESTION_MERGED = "QUESTION_MERGED"
    QUESTION_UNMERGED = "QUESTION_UNMERGED"
    CANONICAL_ANSWER_CHANGED = "CANONICAL_ANSWER_CHANGED"
    DUPLICATE_SUGGESTED = "DUPLICATE_SUGGESTED"
    DUPLICATE_SUGGESTION_ACCEPTED = "DUPLICATE_SUGGESTION_ACCEPTED"
    DUPLICATE_SUGGESTION_REJECTED = "DUPLICATE_SUGGESTION_REJECTED"
    TEAM_CREATED = "TEAM_CREATED"
    TEAM_UPDATED = "TEAM_UPDATED"
    TEAM_MEMBER_ADDED = "TEAM_MEMBER_ADDED"
    TEAM_MEMBER_REMOVED = "TEAM_MEMBER_REMOVED"
    USER_PRIMARY_DEPARTMENT_CHANGED = "USER_PRIMARY_DEPARTMENT_CHANGED"
    GUIDED_TEMPLATE_CREATED = "GUIDED_TEMPLATE_CREATED"
    GUIDED_TEMPLATE_UPDATED = "GUIDED_TEMPLATE_UPDATED"
    GUIDED_TEMPLATE_VERSION_CREATED = "GUIDED_TEMPLATE_VERSION_CREATED"
    GUIDED_TEMPLATE_ARCHIVED = "GUIDED_TEMPLATE_ARCHIVED"
    GUIDED_SESSION_CREATED = "GUIDED_SESSION_CREATED"
    GUIDED_SESSION_STARTED = "GUIDED_SESSION_STARTED"
    GUIDED_SESSION_COMPLETED = "GUIDED_SESSION_COMPLETED"
    GUIDED_SESSION_ARCHIVED = "GUIDED_SESSION_ARCHIVED"
    GUIDED_PARTICIPANT_ADDED = "GUIDED_PARTICIPANT_ADDED"
    GUIDED_PARTICIPANT_UPDATED = "GUIDED_PARTICIPANT_UPDATED"
    GUIDED_PARTICIPANT_REMOVED = "GUIDED_PARTICIPANT_REMOVED"
    GUIDED_SHARED_QUESTION_ADDED = "GUIDED_SHARED_QUESTION_ADDED"
    GUIDED_PARTICIPANT_QUESTION_ADDED = "GUIDED_PARTICIPANT_QUESTION_ADDED"
    GUIDED_FOLLOWUP_ADDED = "GUIDED_FOLLOWUP_ADDED"
    GUIDED_QUESTION_UPDATED = "GUIDED_QUESTION_UPDATED"
    GUIDED_QUESTION_DELETED = "GUIDED_QUESTION_DELETED"
    GUIDED_QUESTION_RESTORED = "GUIDED_QUESTION_RESTORED"
    GUIDED_ANSWER_ADDED = "GUIDED_ANSWER_ADDED"
    GUIDED_ANSWER_UPDATED = "GUIDED_ANSWER_UPDATED"
    GUIDED_LEGACY_IMPORT = "GUIDED_LEGACY_IMPORT"
    KNOWLEDGE_PROPOSAL_CREATED = "KNOWLEDGE_PROPOSAL_CREATED"
    KNOWLEDGE_PROPOSAL_ACCEPTED = "KNOWLEDGE_PROPOSAL_ACCEPTED"
    KNOWLEDGE_PROPOSAL_REJECTED = "KNOWLEDGE_PROPOSAL_REJECTED"
    KNOWLEDGE_PROPOSAL_LINKED_TO_EXISTING = "KNOWLEDGE_PROPOSAL_LINKED_TO_EXISTING"


class AuditEvent(UUIDPrimaryKeyMixin, Base):
    __tablename__ = "audit_events"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("organisations.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    actor_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        index=True,
        nullable=False,
    )
    action: Mapped[str] = mapped_column(String(80), index=True, nullable=False)
    entity_type: Mapped[str] = mapped_column(String(80), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), nullable=False)
    event_metadata: Mapped[dict | None] = mapped_column("metadata", JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )